name: test

env:
  FORCE_COLOR: 1

on:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - v*
    paths-ignore:
      - "docs/**"
      - "**/README.md"
      - "**/CHANGELOG.md"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "docs/**"
      - "**/*.md"

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          check-latest: true
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
